version: "3"

services:

    redis:
        container_name: laravel-redis
        image: redis:4-alpine
        ports:
          - "9998:6379"
        restart: on-failure

    smtp:
      container_name: laravel-mailhog
      image: mailhog/mailhog
      ports:
        - "1025:1025"
        - "8025:8025"
      environment:
        TZ: "America/Detroit"
        command: >
          apk --update add curl bash nano tzdata && >
          cp /usr/share/zoneinfo/Europe/Stockholm /etc/localtime && >
          echo "Europe/Stockholm" > /etc/timezone && >
          apk del tzdata && >
          rm -r /var/cache/apk/* && >
          mkdir -p /usr/share/zoneinfo/Europe && >
          ln -s /etc/localtime /usr/share/zoneinfo/Europe/Stockholm

